### ISSUE TITLE
Region Extractor fails to converge in some cases

### ISSUE THREAD

**Issue by bthirion** [nilearn/nilearn#938]
The following code yields does not  converge on my box:

```
from nilearn import datasets
from nilearn.regions import RegionExtractor
localizer_dataset = datasets.fetch_localizer_contrasts(
    ["checkerboard", "horizontal checkerboard", "vertical checkerboard"],
    n_subjects=1, get_tmaps=True, get_masks=True)
extraction = RegionExtractor(localizer_dataset.tmaps, min_region_size=100,
                             threshold=98, thresholding_strategy='percentile')
extraction.fit()
```

Does somebody understand what's going on ?

**Comment by KamalakerDadi** [comment]
I will check

**Comment by KamalakerDadi** [comment]
Quickly checking, I see some NAN values may be thats causing not converging ?

**Comment by GaelVaroquaux** [comment]
So we need to convert NaNs to zeros.

**Comment by bthirion** [comment]
I've tried with images from one contrast across subjects (also with NaNs) and did not get the problem.

**Comment by KamalakerDadi** [comment]
> I've tried with images from one contrast across subjects (also with NaNs) and did not get the problem.

Just curious, which contrast ?

**Comment by bthirion** [comment]
'left button press (auditory cue)'
See https://github.com/nilearn/nilearn/blob/master/examples/manipulating_visualizing/plot_localizer_mass_univariate_methods.py

**Comment by KamalakerDadi** [comment]
> 'left button press (auditory cue)'

I don't see NANs in this contrast. 

> So we need to convert NaNs to zeros.

May be fix for this kid of bug would be as @GaelVaroquaux said to convert NANs to zeros.

**Comment by bthirion** [comment]
Hmm, I see. This is really weird that NaNs are present in certain t maps to denote backgreound, but not all of them...

**Comment by bthirion** [comment]
One step further:
```
localizer_dataset = datasets.fetch_localizer_contrasts(
    ["checkerboard", "horizontal checkerboard", "vertical checkerboard"],
    n_subjects=1, get_tmaps=True, get_masks=True)
import nibabel as nib
imgs = []
for img in localizer_dataset.tmaps:
    data = nib.load(img).get_data()
    data[np.isnan(data)] = 0
    imgs.append(nib.Nifti1Image(data, nib.load(img).get_affine()))

extraction = RegionExtractor(imgs, min_region_size=100,
                             threshold=98, thresholding_strategy='percentile')
extraction.fit()
```
triggers an Error.

**Comment by AlexandreAbraham** [comment]
We just checked that and this is a scikit-image issue when a seed is alone in the image (all the values around are masked).

**Comment by KamalakerDadi** [comment]
Side note:
slightly reducing threshold from 98 -> 95 worked. No error triggered. We are trying to reproduce with scikit-image and report a bug issue.

![bert_issue](https://cloud.githubusercontent.com/assets/11410385/12322102/6c701fa0-bab2-11e5-8900-b5a6d7c24deb.png)

**Comment by AlexandreAbraham** [comment]
The issue is there: https://github.com/scikit-image/scikit-image/issues/1875

**Comment by bthirion** [comment]
This is great, thanks. 
Since we're at it, here is another sample image that triggers an error: https://transfert.inria.fr/fichiers/2382a74e545211398cfdc28c6284e333/mental-random.nii.gz 
Best, 

Bertrand

**Comment by AlexandreAbraham** [comment]
> Since we're at it, here is another sample image that triggers an error: https://transfert.inria.fr/fichiers/2382a74e545211398cfdc28c6284e333/mental-random.nii.gz

Isnt'it the same error?

**Comment by bthirion** [comment]
No, it's a different one.

**Comment by AlexandreAbraham** [comment]
Can you post it or a snippet? Because I can't reproduce.

**Comment by KamalakerDadi** [comment]
```python
from nilearn.image import threshold_img
from nilearn.regions import connected_regions

img = 'mental-random.nii.gz'
threshold_maps = threshold_img(img, threshold='98%')
regions_img, ind = connected_regions(threshold_maps, extract_type='local_regions', min_region_size=150)
```
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-a25e93b56148> in <module>()
----> 1 regions_img, ind = connected_regions(threshold_maps, extract_type='local_regions', min_region_size=150)

/home/kamalakar/Kamalakar/work/nilearn/nilearn/regions/region_extractor.pyc in connected_regions(maps_img, min_region_size, extract_type, smoothing_fwhm, mask_img)
    147             # Assign -1 to values which are 0. to indicate to ignore
    148             seeds_label[map_3d == 0.] = -1
--> 149             rw_maps = _random_walker(map_3d, seeds_label)
    150             # Now simply replace "-1" with "0" for regions separation
    151             rw_maps[rw_maps == -1] = 0.

/home/kamalakar/Kamalakar/work/nilearn/nilearn/_utils/segmentation.py in _random_walker(data, labels, beta, tol, copy, spacing)
    280     labels = np.atleast_3d(labels)
    281     if np.any(labels < 0):
--> 282         lap_sparse = _build_laplacian(data, spacing, mask=labels >= 0, beta=beta)
    283     else:
    284         lap_sparse = _build_laplacian(data, spacing, beta=beta)

/home/kamalakar/Kamalakar/work/nilearn/nilearn/_utils/segmentation.py in _build_laplacian(data, spacing, mask, beta)
    146     weights = _compute_weights_3d(data, spacing, beta=beta, eps=1.e-10)
    147     if mask is not None:
--> 148         edges, weights = _mask_edges_weights(edges, weights, mask)
    149     lap = _make_laplacian_sparse(edges, weights)
    150     del edges, weights

/home/kamalakar/Kamalakar/work/nilearn/nilearn/_utils/segmentation.py in _mask_edges_weights(edges, weights, mask)
    133     ind_mask = np.logical_and(mask0, mask1)
    134     edges, weights = edges[:, ind_mask], weights[ind_mask]
--> 135     max_node_index = edges.max()
    136     # Reassign edges labels to 0, 1, ... edges_number - 1
    137     order = np.searchsorted(np.unique(edges.ravel()),

/home/kamalakar/anaconda/lib/python2.7/site-packages/numpy/core/_methods.pyc in _amax(a, axis, out, keepdims)
     24 # small reductions
     25 def _amax(a, axis=None, out=None, keepdims=False):
---> 26     return umr_maximum(a, axis, None, out, keepdims)
     27 
     28 def _amin(a, axis=None, out=None, keepdims=False):

ValueError: zero-size array to reduction operation maximum which has no identity
```

**Comment by KamalakerDadi** [comment]
At some point, ```labels``` array contains no seed points which gives us failure.

**Comment by AlexandreAbraham** [comment]
Oh, ok, I have reported this error along with the other in my skimage issue.

**Comment by KamalakerDadi** [comment]
Again a side-note, to not to block with bug, ```extract_type=connected_components``` can be used to get an idea on the data. 
```python
regions_img, ind = connected_regions(threshold_maps, extract_type='connected_components', min_region_size=150)
```

**Comment by bthirion** [comment]
In your snippet, what are threshold_maps: already thresholded maps ?
If I dot it, I get a 
ValueError: The given input to threshold is not valid. Please submit a valid number specific to either of the strategy in ['ratio_n_voxels', 'img_value', 'percentile']

**Comment by KamalakerDadi** [comment]
```python
from nilearn import plotting
from nilearn.image import threshold_img
from nilearn.regions import connected_regions

img = 'mental-random.nii.gz'
# threshold should be in string if you are using 'percentile', by default strategy is 'percentile'
threshold_stat_img = threshold_img(img, threshold='98%') 
regions_img, index = connected_regions(threshold_stat_img, extract_type='connected_components', min_region_size=150)
plotting.plot_prob_atlas(regions_img)
```

**Comment by bthirion** [comment]
All right, thanks.

**Comment by KamalakerDadi** [comment]
In case if you missed it: there is an example made for 3D stat image.

http://nilearn.github.io/auto_examples/manipulating_visualizing/plot_extract_rois_statistical_maps.html#sphx-glr-auto-examples-manipulating-visualizing-plot-extract-rois-statistical-maps-py

**Comment by GaelVaroquaux** [comment]
Has this been fixed by @KamalakerDadi 's recent improvements (merged in master)?

**Comment by KamalakerDadi** [comment]
Yes, merged in master which means this issue is partially fixed. 

This is still remained https://github.com/scikit-image/scikit-image/issues/1875

**Comment by AlexandreAbraham** [comment]
> Yes, merged in master which means this issue is partially fixed.

NaN problem is fixed. But problem of lonely seeds remain. I can fix it but only next week because I'm busy.

**Comment by banilo** [comment]
> NaN problem is fixed. But problem of lonely seeds remain.

Sorry, but you sound like yoda here :-P

![image](https://cloud.githubusercontent.com/assets/3907396/12479515/d5648e40-c03b-11e5-95b6-3c1d622e9390.png)

**Comment by KamalakerDadi** [comment]
> I can fix it but only next week because I'm busy.

@AlexandreAbraham Can you propose your idea or hint ?

**Comment by AlexandreAbraham** [comment]
> @AlexandreAbraham Can you propose your idea or hint ?

We are discussing it in the skimage issue.

**Comment by lisigiuseppe** [comment]
The issue has been closed on the skimage side. 
However, it is not fixed on the nilearn side. 
Indeed in the nilearn/_utils/segmentation.py you can see the following comment:
> This code is mostly adapted from scikit-image 0.11.3 release.
Location of file in scikit image: random_walker function and its suporting
sub functions in skimage.segmentation

However, I am not sure where to modify the file. 
Is there anyone who knows how to fix this?

**Comment by KamalakerDadi** [comment]
@lisigiuseppe You are right. We need to update the backported code. Let me have a look and tell you where to fix this. Will you be able to file a PR ?

**Comment by KamalakerDadi** [comment]
Seems like issue is still open in scikit image ?

**Comment by NicolasGensollen** [comment]
I had a look at this today. First of all, I can't reproduce the second error because the link to download the input file `mental-random.nii.gz` seems to be broken. If someone can provide it or give a new link, I'd be happy to test on it.

However, looking at the issue on scikit image, I was able to get the following error:

```python
import numpy as np
from nilearn._utils.segmentation import _random_walker

data = np.random.random((3, 3))
# Build the following labels with an isolated seed
# in the bottom-right corner:
# array([[ 0.,  1., -1.],
#        [-1., -1., -1.],
#        [-1., -1.,  2.]])
labels = -np.ones((3, 3))
# Make a seed
labels[0, 1] = 1
# Point next to the seed
labels[0, 0] = 0
# Set a seed in the middle, it is surrounded by masked pixels
labels[2, 2] = 2
print( _random_walker(data, labels))
```
Which gives me:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-5-0492425f4ffe> in <module>
----> 1 _random_walker(data, labels)

~/GitRepos/nilearn-fork/nilearn/_utils/segmentation.py in _random_walker(data, labels, beta, tol, copy, spacing)
    284         lap_sparse = _build_laplacian(data, spacing, beta=beta)
    285 
--> 286     lap_sparse, B = _buildAB(lap_sparse, labels)
    287 
    288     # We solve the linear system

~/GitRepos/nilearn-fork/nilearn/_utils/segmentation.py in _buildAB(lap_sparse, labels)
    110     seeds_indices = indices[labels > 0]
    111     # The following two lines take most of the time in this function
--> 112     B = lap_sparse[unlabeled_indices][:, seeds_indices]
    113     lap_sparse = lap_sparse[unlabeled_indices][:, unlabeled_indices]
    114     nlabels = labels.max()

~/anaconda3/envs/nilearn/lib/python3.8/site-packages/scipy/sparse/_index.py in __getitem__(self, key)
     31     """
     32     def __getitem__(self, key):
---> 33         row, col = self._validate_indices(key)
     34         # Dispatch to specialized methods.
     35         if isinstance(row, INT_TYPES):

~/anaconda3/envs/nilearn/lib/python3.8/site-packages/scipy/sparse/_index.py in _validate_indices(self, key)
    144                 col += N
    145         elif not isinstance(col, slice):
--> 146             col = self._asindices(col, N)
    147 
    148         return row, col

~/anaconda3/envs/nilearn/lib/python3.8/site-packages/scipy/sparse/_index.py in _asindices(self, idx, length)
    167         max_indx = x.max()
    168         if max_indx >= length:
--> 169             raise IndexError('index (%d) out of range' % max_indx)
    170 
    171         min_indx = x.min()

IndexError: index (2) out of range
```

Looking more closely, it seems like the random walker is not handling the following edge cases properly:

- No label provided (all elements of labels array are zeros)
- Isolated seeds (that is seeds disconnected from zero-labelled pixels)
- All labels become -1 after cleaning (very edgy but possible I guess...)

while it handles the case with isolated zero-label pixels correctly by setting them to -1 (these pixels cannot be determined since there is no path to a seed label).

In #2639 I propose a possible fix with the following behaviour:

- return provided labels for desperate edge cases (all zeros, all -1...)
- ignore isolated seeds (replace them with -1) in the same way isolated zero-labelled pixels are handled.

Any idea on a better approach?

**Comment by bthirion** [comment]
> First of all, I can't reproduce the second error because the link to download the input file `mental-random.nii.gz` seems to be broken.

Sure. I think it's fine to close that one with #2639. I'll open a new issue if I hit another issue ;-)

**Comment by NicolasGensollen** [comment]
Addressed in #2639

**Comment by GaelVaroquaux** [comment]
That's nice!!

On Tue, Jan 05, 2021 at 06:53:43AM -0800, Gensollen wrote:
> Addressed in #2639

> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
    Gael Varoquaux
    Research Director, INRIA		  Visiting professor, McGill 
    http://gael-varoquaux.info            http://twitter.com/GaelVaroquaux
